### ISSUE TITLE
Conflict with Catalogue

### ISSUE THREAD

**Issue by KhanhPham05** [celsiusqc/Create-Addon#2]
Crash when open mod details via new mod list gui from Catalogue
Crash Report: update soon

**Comment by MrCrayfish** [comment]
Issue is related to `Item#hasEffect` in the Drill Item. It's assuming the player is not null when it can be if not in the game.

**Comment by MrCrayfish** [comment]
Crash log since it wasn't included https://pastebin.com/UeYPtDNZ
